### PR TITLE
feat: Adds Transit Gateway CIDR Block argument

### PR DESCRIPTION
**Pull request by amenocal**
## Description
Provides the ability to pass in the variable to send to the Transit Gateway Module the list of associated CIDR blocks.

## Motivation and Context
With the update on [Provider 4.4.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.4.0) the [Transit Gateway Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway) provides the ability to send `transit_gateway_cidr_blocks` 

For those users using the `latest` version of the provider and having added the cidr blocks through the AWS Console, using this module won't try to remove the cidr block range.

## Breaking Changes
None.

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have tested and validated these changes with terraform plan and apply in example/complete/* project and running it with and without providing the argument. Validated in my own dev environment

### CODE REVIEW

**Comment by amenocal** [comment]
@antonbabenko can you take a look at this PR and let me know if I'm missing something ? Thanks!

**Comment by benguichard** [comment]
Hi @antonbabenko, is it possible to take a look on that MR ? Many thanks

**Comment by bryantbiggs** [comment]
as stated in the PR description, we'll have to update the [minimum supported provider version](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/blob/e6ceb860e13f60db2df99e6bfe666a4037f80e82/versions.tf#L5) to v4.4.0 and we should update an example (probably `complete`) to validate and demonstrate this new features usage https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/tree/master/examples

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.7.0 :tada:

**Pull request closed without merging**
