### PR TITLE
fix: Added support for multi-account deployments

### LINKED ISSUE #19: Module do not accept RAM Resource in remote AWS Account
Currently transit gateway module implementation do not work correctly if used to deploy it multiple account.

Transit Gateway is correctly created in one account but RAM requires that we accept resources from remote account before Transit Gateway is visible in shared AWS Account.
If share is not visible code deploys another Transit Gateway which is not what you would expect to happen.

Module should be able to create just VPC attachment in separate account and should be able to auto accept RAM Share in another AWS Account.

### PR DESCRIPTION
**Pull request by szpuni**
This commit fixes #19 #14 #15

## Description

This PR Implements RAM Accepter in another AWS account when multi account is used. This is required to install VPC Attachment and if this is not done attachment cannot find it and it attempts to create new Transit Gateway.
This PR also attempts to fix issue in line 70 where when create_tgw is false lookup condition default value cannot be evaluated since transit gateway is not being created.
Added new example sections which extends complete example so users know how to deploy this solution if multi account is used.

## Motivation and Context

This PR attempts to implement or fix issues  #19 #14 #15

## How Has This Been Tested?

Transit gateway deployed in multiple scenarios (single and multiple account) with combination of feature flags to make sure it's working as desired.

### CODE REVIEW

**Comment by gschaffer-cxn** [comment]
@szpuni could you please fix the Semantic pull request issue, so @antonbabenko can review it and all the things are green?

**Comment by szpuni** [comment]
@gschaffer-cxn sure I wasn't really sure what is that semantic pull request so needed to quickly educate my self. Hope this is corrected now

**Comment by gschaffer-cxn** [comment]
@antonbabenko could you review this PR pls?

**Comment by antonbabenko** [comment]
Thanks @szpuni and @gschaffer-cxn for this PR!

I don't have a lot of time for this module because I don't use it so much with my customers anymore.

[v1.3.0](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/releases/v1.3.0) has been just released.

PS: I have not run examples to verify, so please give it a try for real and please confirm that linked issues can also be closed.

**Comment by szpuni** [comment]
Hi @antonbabenko thanks for this merge. I actually used it recently and it did work just fine. I saw you have removed profile name from example. I think this is required since this code connects to 2 accounts at the same time. Only way I found so far was by connecting to 2 AWS accounts and using profile name of each account inserted into aws provider so terraform knows where to connect.

Anyway thanks for this merge and I hope everything will be just fine 👍

**Comment by antonbabenko** [comment]
Code in `examples` ideally should be executable as-is, but in the case of multiple providers, there should be some changes anyway (somebody may use `profile`, but others may use env variables).

Good to know that it works for you, I will go ahead and close the related issues.

**Comment by szpuni** [comment]
Cool thanks and yes you right it example should be generic so it can work with anybody.

**Pull request merged**
