### PR TITLE
feat: additional TGW route per subnet

### PR DESCRIPTION
**Pull request by daniel-ciaglia**
## Description
The change allows to create routes to the TGW for given route_tables.

## Motivation and Context
When using the [terraform-aws-modules/terraform-aws-vpc module](https://github.com/terraform-aws-modules/terraform-aws-vpc) AND VPC endpoints or NAT GWs, each subnet created will be associated with its own routing table. *This makes the default VPC routing table unused*.
With the help of these additional information, we are creating routes in all provided route tables.

## Breaking Changes
None

## How Has This Been Tested?
It's live in our staging environment.
3 VPC created with the mentioned VPC module (2 regions)
NAT gateways and VPC endpoints in place - thus we get route tables per subnets.
set up 2 TGW

### CODE REVIEW

**Comment by daniel-ciaglia** [comment]
Do you mind to check this, @antonbabenko?

**Comment by tfhartmann** [comment]
@daniel-ciaglia would you mind resolving the merge conflicts?

**Comment by daniel-ciaglia** [comment]
@tfhartmann - Done

**Comment by tfhartmann** [comment]
🤔  When I run  ` pre-commit run -a` I see a failure on docs, but not on the stuff in the above checks... @antonbabenko  Do you have a sense of whats up with the failing checks?

**Comment by antonbabenko** [comment]
It can be related that "This branch is out-of-date with the base branch" and/or there is something wrong going on on GH Actions lately (related - https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/pull/38#issuecomment-855918610 , cc @bryantbiggs ).

PS: This PR was opened from the organization's fork (`TierMobility`), we won't be able to push into it. I normally open exactly the same PR and close the original one with the comment. Let me know if you know a better way.

**Pull request closed without merging**
