### PR TITLE
fix: Update map function to work in Terraform 0.15

### PR DESCRIPTION
**Pull request by matthewrkrieger**
## Description
Update call to deprecated `map` function to use `tomap` instead

## Motivation and Context
Resolves https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/issues/43

https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers

## Breaking Changes
Will break Terraform <0.12

## How Has This Been Tested?
- [x] I have tested and validated these changes using the `examples/complete` project

```
$ terraform version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0
```

### CODE REVIEW

**Comment by antonbabenko** [comment]
@bryantbiggs Do you know what is going on with failed GH Actions / terraform_docs?

**Comment by bryantbiggs** [comment]
@antonbabenko it looks to be working as expected https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/45 - the only thing that looks slightly different here is that @matthewrkrieger is a first time contributor and Github doesn't automatically run actions for first time contributors without approval first

image

**Comment by antonbabenko** [comment]
@bryantbiggs https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/runs/2511351637 - this one, it was for commit 7c7febb which failed.

**Comment by antonbabenko** [comment]
Thanks, @matthewrkrieger !

[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/releases/v2.1.0) has been just released.

**Pull request merged**
