### PR TITLE
wip: add feature of transit route tables using map of interconnections

### PR DESCRIPTION
**Pull request by zelig81**
# Description

- add possibility to create multiple transit route tables with some custom mapping of interconnections
- add possibility to create routes to tgw in vpc route tables chosen by tag set
- add attaching VPNs (without it's creation)
- support backward compatibility of previous versions
- add example
- add documentation

solving [issue#1](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/issues/1)

### CODE REVIEW

**Comment by zelig81** [comment]
@putarpuar thank you for the feedback - hope to return to it in the near future

**Comment by jwitko** [comment]
Hey @zelig81 , I ended up trying this out by bringing the module local.  There were a couple merge conflicts that were easy enough to resolve and then a few things I'm guessing were issues because you were using an older terraform version.  I'm now using it successfully on the latest TF 0.13.x.   
Besides doing all of the above do you have other things required to get this off  `wip`?  Would you accept an MR from me to your forked branch?

**Comment by zelig81** [comment]
> Hey @zelig81 , I ended up trying this out by bringing the module local. There were a couple merge conflicts that were easy enough to resolve and then a few things I'm guessing were issues because you were using an older terraform version. I'm now using it successfully on the latest TF 0.13.x.
> Besides doing all of the above do you have other things required to get this off `wip`? Would you accept an MR from me to your forked branch?
@jwitko Thank you Jason - your help will be most helpful. The things that made me put 'wip' on the PR were: 
- the need to generate VPN if VPN ids were not provided
- race condition while launching the module in pure terraform (without terragrunt) for vpc modules. In terragrunt it is solved out of the box

**Comment by zelig81** [comment]
Sorry - closed by mistake

**Pull request closed without merging**
