### PR TITLE
feat: Allow creating VPC routes for already existing or shared TGW

### PR DESCRIPTION
**Pull request by kamilhristov**
## Description
These changes allow the creation of VPC routes for already existing or shared TGWs via `tgw_id` that already exists without changing the input variables.

## Motivation and Context
Currently, VPC routes can point only to the transit gateway created by the module itself.

## Breaking Changes
No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by Kostadin-Lazarov — APPROVED** [review]

**Comment by Kostadin-Lazarov** [comment]
Given that this PR is currently blocking our production deployment, could we please move forward and merge the PR?

**Comment by kamilhristov** [comment]
@antonbabenko ping

**Comment by Kostadin-Lazarov** [comment]
@antonbabenko ping

**Comment by TLPNull** [comment]
I am starting to use this module now, is the project dead? I am having the same issue

**Review by bryantbiggs — APPROVED** [review]
thank you

**Pull request merged**
